### ISSUE TITLE
JSHint failed for: /resources/assets/angular/controllers.js, /resources/assets/angular/main-angular.js

### ISSUE THREAD

**Issue by Rolando-Barbella** [HRcc/laravel-elixir-angular#7]
Hi There, I am following the  readme instructions, but it is giving an error to do with JSHint. I'm aslo kid of new to Gulp.

My gulpfile looks like:

``` javascript
var elixir = require('laravel-elixir');
var gulp = require('gulp');
require('laravel-elixir-angular');

/*
 |--------------------------------------------------------------------------
 | Elixir Asset Management
 |--------------------------------------------------------------------------
 |
 | Elixir provides a clean, fluent API for defining some basic Gulp tasks
 | for your Laravel application. By default, we are compiling the Less
 | file for our application, as well as publishing vendor resources.
 |
 */

var paths = {
  jquery: 'vendor/bower_components/jquery/',
  angular:'vendor/bower_components/angular/',
  bootstrap: 'vendor/bower_components/bootstrap-sass-official/assets/',
}

elixir(function(mix) {
  mix.angular();
  mix.sass('style.scss','public/css/')
    .copy(paths.bootstrap + 'fonts/bootstrap/**', 'public/fonts')
    .copy(paths.bootstrap + 'stylesheets/**', 'public/css')
    .scripts([
      paths.jquery + 'dist/jquery.js',
      paths.bootstrap + 'javascripts/bootstrap.js',
      paths.angular + 'angular.min.js'
    ],'public/js/app.js', './');
});

```

My main-angular.js file looks like:

``` javascript

'use strict'
angular.module('myApp',[]);
```

I will much appreciate your help :)

**Comment by Rolando-Barbella** [comment]
I kind of fixed, it is taking the angular files, but now it's giving me the following error when I run gulp watch:

'watch-assets' errored after 10 ms
[10:19:16] Error: watch ENOSPC
    at errnoException (fs.js:1030:11)
    at FSWatcher.start (fs.js:1062:11)
    at Object.fs.watch (fs.js:1087:11)
    at Gaze._watchDir (/home/rolando/Documents/Projects/Ocupassion/training/subscribe/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:289:30)
    at /home/rolando/Documents/Projects/Ocupassion/training/subscribe/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:358:10
    at iterate (/home/rolando/Documents/Projects/Ocupassion/training/subscribe/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
    at Object.forEachSeries (/home/rolando/Documents/Projects/Ocupassion/training/subscribe/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:66:3)
    at Gaze._initWatched (/home/rolando/Documents/Projects/Ocupassion/training/subscribe/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:354:10)
    at Gaze.add (/home/rolando/Documents/Projects/Ocupassion/training/subscribe/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:177:8)
    at new Gaze (/home/rolando/Documents/Projects/Ocupassion/training/subscribe/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:74:10)
Error running task sequence: { task: 'watch-assets',
  message: 'watch-assets catch',
  duration: 0.010231995,
  hrDuration: [ 0, 10231995 ],
  err: { [Error: watch ENOSPC] code: 'ENOSPC', errno: 'ENOSPC', syscall: 'watch' } }

My updated gulpfile is:

``` javascript
var elixir = require('laravel-elixir');
var gulp = require('gulp');
require('laravel-elixir-angular');
require('laravel-elixir-sass-compass');

/*
 |--------------------------------------------------------------------------
 | Elixir Asset Management
 |--------------------------------------------------------------------------
 |
 | Elixir provides a clean, fluent API for defining some basic Gulp tasks
 | for your Laravel application. By default, we are compiling the Less
 | file for our application, as well as publishing vendor resources.
 |
 */

var paths = {
  jquery: 'vendor/bower_components/jquery/',
  angular:'vendor/bower_components/angular/',
  bootstrap: 'vendor/bower_components/bootstrap-sass-official/assets/',
}

elixir(function(mix) {
  mix.angular("resources/assets/angular/", "public/js/", "application.js");
  mix.sass('style.scss','public/css/')
    .copy(paths.bootstrap + 'fonts/bootstrap/**', 'public/fonts')
    .copy(paths.bootstrap + 'stylesheets/**', 'public/css')
    .scripts([
      paths.jquery + 'dist/jquery.js',
      paths.bootstrap + 'javascripts/bootstrap.js',
      paths.angular + 'angular.min.js'
    ],'public/js/app.js', './');
});

```
