### ISSUE TITLE
Please migrate to laravel-elixir v3

### ISSUE THREAD

**Issue by semsphy** [HRcc/laravel-elixir-angular#9]
``` nodejs

TypeError: Object function (recipe) {
    // We'll start by loading all of the available tasks.
    require('require-dir')('./tasks');

    // Next, we'll reset all tasks. This is mostly for tests.
    Elixir.tasks = Elixir.config.tasks = [];

    // The user may then choose which tasks they want.
    recipe(Elixir.mixins);

    // Now that the user has requested their desired tasks
    // from the Gulpfile, we'll initialize everything!
    createGulpTasks.call(Elixir);
} has no method 'registerWatcher'
    at Function.<anonymous> (/media/DataCenter/projects/guiddies/node_modules/laravel-elixir-angular/index.js:49:10)
    at Function.<anonymous> (/media/DataCenter/projects/guiddies/node_modules/laravel-elixir/index.js:46:18)
    at /media/DataCenter/projects/guiddies/gulpfile.js:180:10
    at Elixir (/media/DataCenter/projects/guiddies/node_modules/laravel-elixir/index.js:20:5)
    at Object.<anonymous> (/media/DataCenter/projects/guiddies/gulpfile.js:173:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

```

Thanks,

**Comment by rudowastaken** [comment]
It's done. Please update your dependencies to `"laravel-elixir-angular": "^1"` or something similar, since the newest release is `1.0.1`.

**Comment by semsphy** [comment]
Thank you very much.
